# -*- coding: utf-8 -*-
"""Mini_project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t92U-XD8rs5oh7JzMBnOTNjJzmlVWCQZ

Decision Tree Regressor
"""

from google.colab import drive
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve, auc
from scipy import interp

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

from google.colab import drive
drive.mount('../content/drive')

dataset = pd.read_csv('/content/drive/MyDrive/seeds_dataset_final.csv')

dataset = dataset.sample(frac=1)

dataset.head()

dataset.describe()

X=dataset.drop('h', axis = 1)
y=dataset['h']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

"""KNN classifier"""

import numpy as np
import pandas as pd

knn_dataset = pd.read_csv('/content/drive/MyDrive/seeds_dataset_final.csv')

knn_dataset

features = [["a", "b", "c", "d", "e", "f", "g"]]
scaler = StandardScaler()
for feature in features:
    dataset[feature] = scaler.fit_transform(dataset[feature])

knn_dataset.head()

knn_dataset.shape

knn_dataset.isnull().sum

from sklearn.neighbors import KNeighborsClassifier

X = dataset.iloc[:,:7]
y = dataset['h']

X

y

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.2,random_state=42)

print(f'The length of train X is {len(train_X)} and the lenght of train y is {len(train_y)}')

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(train_X,train_y)

test_y

pred = knn.predict(test_X)

from sklearn.metrics import accuracy_score

accuracy_score = accuracy_score(test_y, pred)

print(accuracy_score)

from sklearn.metrics import classification_report, confusion_matrix
matrix_confusion = confusion_matrix(test_y, pred)
print(classification_report(test_y, pred))
sns.heatmap(matrix_confusion, square=True, annot=True, cmap='Blues', fmt='d', cbar=False)

"""Random Forest Classifier


"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('../content/drive')

features = pd.read_csv('/content/drive/MyDrive/seeds_dataset_final.csv')

features.head(5)

features.describe()

labels = np.array(features['h'])

# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('h', axis=1)

# Saving feature names for later use
feature_list = list(features.columns)

# Convert to numpy array
features = np.array(features)

from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

print('The baseline performance of predicting the most prevalent class is of approximately 28%. as mentioned in the source website')

from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

# Train the model on training data
rf.fit(train_features, train_labels);

# Use the forest's predict method on the test data
predictions = rf.predict(test_features)

# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / test_labels)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')